/*
 * Generated by ISE 14.05.9.5158 GPL Edition - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F167_3997();
extern void F171_4260();
extern void F165_3924();
extern void F170_4169();
extern void F190_2125();
extern void F188_3804();
extern void F22_496();
extern EIF_REFERENCE F22_483();
extern EIF_BOOLEAN F22_495();
extern EIF_BOOLEAN F22_500();
extern void F22_505();
extern void F22_506();
extern void F22_507();
extern void F31_641();
extern EIF_TYPED_VALUE F31_642();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F167_3997;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F165_3924;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F190_2125;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F171_4260;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F170_4169;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F188_3804;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F22_496;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F22_495;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F22_483;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F22_500;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F22_505;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F22_506;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F22_507;

	egc_str_dtype = 170;

	egc_str32_dtype = 169;
	egc_arr_dtype = 189;
	egc_tup_dtype = 119;
	egc_disp_rout_id = 866;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)676;
	egc_sp_wchar = (EIF_TYPE_INDEX)652;
	egc_sp_bool = (EIF_TYPE_INDEX)567;
	egc_sp_uint8 = (EIF_TYPE_INDEX)528;
	egc_sp_uint16 = (EIF_TYPE_INDEX)474;
	egc_sp_uint32 = (EIF_TYPE_INDEX)428;
	egc_sp_uint64 = (EIF_TYPE_INDEX)329;
	egc_sp_int8 = (EIF_TYPE_INDEX)65535;
	egc_sp_int16 = (EIF_TYPE_INDEX)65535;
	egc_sp_int32 = (EIF_TYPE_INDEX)277;
	egc_sp_int64 = (EIF_TYPE_INDEX)65535;
	egc_sp_real32 = (EIF_TYPE_INDEX)372;
	egc_sp_real64 = (EIF_TYPE_INDEX)313;
	egc_sp_pointer = (EIF_TYPE_INDEX)252;
	egc_sp_ref = (EIF_TYPE_INDEX)177;

	egc_uint8_dtype = 139;
	egc_uint16_dtype = 136;
	egc_uint32_dtype = 133;
	egc_uint64_dtype = 130;
	egc_int8_dtype = 127;
	egc_int16_dtype = 124;
	egc_int32_dtype = 121;
	egc_int64_dtype = 142;
	egc_bool_dtype = 157;
	egc_real32_dtype = 145;
	egc_char_dtype = 154;
	egc_wchar_dtype = 151;
	egc_real64_dtype = 148;
	egc_point_dtype = 160;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 43;
	egc_except_emnger_dtype = 21;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "sample";
	egc_system_location = "C:\\Users\\Manav\\Desktop\\eve_server\\projects\\sample_90799D1A-C197-4822-BEE9-C0D076CA8562\\EIFGENs\\sample\\W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1403868229;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 690;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 1690;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 30;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F31_641;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F31_642;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 113; /* APPLICATION */
	}
}

#ifdef __cplusplus
}
#endif
