/*
 * Generated by ISE 14.05.9.5158 GPL Edition - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"
#include "eoffsets.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F889_17162();
extern void F887_17089();
extern void F722_12306();
extern void F867_16970();
extern void F120_8616();
extern EIF_REFERENCE F120_8603();
extern EIF_BOOLEAN F120_8615();
extern EIF_BOOLEAN F120_8620();
extern void F120_8625();
extern void F120_8626();
extern void F120_8627();
extern void egc_routine_tables_init (void);

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;
extern char *(*R2[])();
extern char *(*R6[])();
extern char *(*R3[])();

extern char *(*R4[])();

extern char *(*R5[])();



extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_REFERENCE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F889_17162;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F887_17089;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_INTEGER)) F722_12306;
	egc_str_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_str32_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str32_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_routdisp_fl = (void (*)(EIF_REFERENCE, EIF_POINTER, EIF_POINTER, EIF_POINTER, EIF_REFERENCE, EIF_BOOLEAN, EIF_INTEGER)) F867_16970;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN, EIF_INTEGER, EIF_INTEGER, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN)) F120_8616;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F120_8615;
	egc_last_exception = (EIF_REFERENCE (*)(EIF_REFERENCE)) F120_8603;
	egc_is_code_ignored = (EIF_BOOLEAN (*)(EIF_REFERENCE, EIF_INTEGER)) F120_8620;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F120_8625;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F120_8626;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F120_8627;

	egc_str_dtype = 892;

	egc_str32_dtype = 891;
	egc_arr_dtype = 721;
	egc_tup_dtype = 823;
	egc_disp_rout_id = 11915;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)961;
	egc_sp_wchar = (EIF_TYPE_INDEX)964;
	egc_sp_bool = (EIF_TYPE_INDEX)956;
	egc_sp_uint8 = (EIF_TYPE_INDEX)963;
	egc_sp_uint16 = (EIF_TYPE_INDEX)962;
	egc_sp_uint32 = (EIF_TYPE_INDEX)959;
	egc_sp_uint64 = (EIF_TYPE_INDEX)957;
	egc_sp_int8 = (EIF_TYPE_INDEX)967;
	egc_sp_int16 = (EIF_TYPE_INDEX)965;
	egc_sp_int32 = (EIF_TYPE_INDEX)954;
	egc_sp_int64 = (EIF_TYPE_INDEX)958;
	egc_sp_real32 = (EIF_TYPE_INDEX)966;
	egc_sp_real64 = (EIF_TYPE_INDEX)955;
	egc_sp_pointer = (EIF_TYPE_INDEX)960;
	egc_sp_ref = (EIF_TYPE_INDEX)953;

	egc_uint8_dtype = 1017;
	egc_uint16_dtype = 1008;
	egc_uint32_dtype = 1005;
	egc_uint64_dtype = 1002;
	egc_int8_dtype = 999;
	egc_int16_dtype = 996;
	egc_int32_dtype = 993;
	egc_int64_dtype = 990;
	egc_bool_dtype = 832;
	egc_real32_dtype = 1011;
	egc_char_dtype = 829;
	egc_wchar_dtype = 826;
	egc_real64_dtype = 1014;
	egc_point_dtype = 865;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 186;
	egc_except_emnger_dtype = 119;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	exception_stack_managed = (EIF_BOOLEAN) 0;
	egc_ecreate = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R2;
	egc_exp_create = (void (**)(EIF_REFERENCE)) R6;
	egc_edispose = (void (**)(void)) R3;
	egc_copy = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R4;
	egc_is_equal = (EIF_BOOLEAN (**)(EIF_REFERENCE, EIF_REFERENCE)) R5;
	egc_ce_rname = egc_ce_rname_init;
	egc_fnbref = egc_fnbref_init;
	egc_fsize = egc_fsize_init;

	egc_system_name = "app";
	egc_system_location = "C:\\Users\\Manav\\Desktop\\eve_server\\server_app\\EIFGENs\\app_nino\\F_code";
	egc_compiler_tag = 38;
	egc_project_version = 1402577930;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 1095;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make_and_launch";
	egc_rcdt[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_routine_tables_init();
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 236; /* APPLICATION */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 577; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 1094; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
