/*
 * Generated by ISE 14.05.9.5158 GPL Edition - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F343_17038();
extern void F347_17301();
extern void F341_16965();
extern void F346_17210();
extern void F460_12199();
extern void F455_16845();
extern void F147_8579();
extern EIF_REFERENCE F147_8566();
extern EIF_BOOLEAN F147_8578();
extern EIF_BOOLEAN F147_8583();
extern void F147_8588();
extern void F147_8589();
extern void F147_8590();
extern void F126_8314();
extern EIF_TYPED_VALUE F126_8315();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F343_17038;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F341_16965;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F460_12199;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F347_17301;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F346_17210;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F455_16845;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F147_8579;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F147_8578;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F147_8566;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F147_8583;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F147_8588;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F147_8589;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F147_8590;

	egc_str_dtype = 346;

	egc_str32_dtype = 345;
	egc_arr_dtype = 459;
	egc_tup_dtype = 325;
	egc_disp_rout_id = 11808;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)754;
	egc_sp_wchar = (EIF_TYPE_INDEX)901;
	egc_sp_bool = (EIF_TYPE_INDEX)626;
	egc_sp_uint8 = (EIF_TYPE_INDEX)822;
	egc_sp_uint16 = (EIF_TYPE_INDEX)1028;
	egc_sp_uint32 = (EIF_TYPE_INDEX)579;
	egc_sp_uint64 = (EIF_TYPE_INDEX)650;
	egc_sp_int8 = (EIF_TYPE_INDEX)681;
	egc_sp_int16 = (EIF_TYPE_INDEX)946;
	egc_sp_int32 = (EIF_TYPE_INDEX)521;
	egc_sp_int64 = (EIF_TYPE_INDEX)862;
	egc_sp_real32 = (EIF_TYPE_INDEX)986;
	egc_sp_real64 = (EIF_TYPE_INDEX)539;
	egc_sp_pointer = (EIF_TYPE_INDEX)736;
	egc_sp_ref = (EIF_TYPE_INDEX)447;

	egc_uint8_dtype = 411;
	egc_uint16_dtype = 402;
	egc_uint32_dtype = 399;
	egc_uint64_dtype = 396;
	egc_int8_dtype = 393;
	egc_int16_dtype = 390;
	egc_int32_dtype = 387;
	egc_int64_dtype = 384;
	egc_bool_dtype = 333;
	egc_real32_dtype = 405;
	egc_char_dtype = 330;
	egc_wchar_dtype = 327;
	egc_real64_dtype = 408;
	egc_point_dtype = 336;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 165;
	egc_except_emnger_dtype = 146;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "app";
	egc_system_location = "C:\\Users\\Manav\\Desktop\\eve_server\\server_app\\EIFGENs\\app_nino\\W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1401786777;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 1085;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make_and_launch";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 9030;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 10893;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 19555;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 125;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F126_8314;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F126_8315;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 215; /* APPLICATION */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 273; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 444; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
