/*
 * Generated by ISE 14.05.9.5158 GPL Edition - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F351_17162();
extern void F355_17425();
extern void F349_17089();
extern void F354_17334();
extern void F468_12306();
extern void F466_16969();
extern void F150_8616();
extern EIF_REFERENCE F150_8603();
extern EIF_BOOLEAN F150_8615();
extern EIF_BOOLEAN F150_8620();
extern void F150_8625();
extern void F150_8626();
extern void F150_8627();
extern void F129_8351();
extern EIF_TYPED_VALUE F129_8352();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F351_17162;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F349_17089;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F468_12306;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F355_17425;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F354_17334;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F466_16969;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F150_8616;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F150_8615;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F150_8603;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F150_8620;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F150_8625;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F150_8626;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F150_8627;

	egc_str_dtype = 354;

	egc_str32_dtype = 353;
	egc_arr_dtype = 467;
	egc_tup_dtype = 333;
	egc_disp_rout_id = 11915;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)769;
	egc_sp_wchar = (EIF_TYPE_INDEX)917;
	egc_sp_bool = (EIF_TYPE_INDEX)604;
	egc_sp_uint8 = (EIF_TYPE_INDEX)865;
	egc_sp_uint16 = (EIF_TYPE_INDEX)847;
	egc_sp_uint32 = (EIF_TYPE_INDEX)720;
	egc_sp_uint64 = (EIF_TYPE_INDEX)625;
	egc_sp_int8 = (EIF_TYPE_INDEX)1029;
	egc_sp_int16 = (EIF_TYPE_INDEX)958;
	egc_sp_int32 = (EIF_TYPE_INDEX)531;
	egc_sp_int64 = (EIF_TYPE_INDEX)658;
	egc_sp_real32 = (EIF_TYPE_INDEX)997;
	egc_sp_real64 = (EIF_TYPE_INDEX)549;
	egc_sp_pointer = (EIF_TYPE_INDEX)747;
	egc_sp_ref = (EIF_TYPE_INDEX)455;

	egc_uint8_dtype = 419;
	egc_uint16_dtype = 410;
	egc_uint32_dtype = 407;
	egc_uint64_dtype = 404;
	egc_int8_dtype = 401;
	egc_int16_dtype = 398;
	egc_int32_dtype = 395;
	egc_int64_dtype = 392;
	egc_bool_dtype = 341;
	egc_real32_dtype = 413;
	egc_char_dtype = 338;
	egc_wchar_dtype = 335;
	egc_real64_dtype = 416;
	egc_point_dtype = 344;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 168;
	egc_except_emnger_dtype = 149;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "app";
	egc_system_location = "C:\\Users\\Manav\\Desktop\\eve_server\\server_app\\EIFGENs\\app_nino\\W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1402577930;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 1093;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make_and_launch";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 9067;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 11000;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 19676;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 128;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F129_8351;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F129_8352;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 219; /* APPLICATION */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 280; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 452; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
